"""changed provincial to origin and added is international means

Revision ID: 058d4bde1e30
Revises: 35de5ed46013
Create Date: 2023-11-24 03:17:04.818979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058d4bde1e30'
down_revision: Union[str, None] = '35de5ed46013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('origin_is_international', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('user', sa.Column('origin_country', sa.String(), server_default='philippines', nullable=True))
    op.add_column('user', sa.Column('origin_region', sa.String(), nullable=True))
    op.add_column('user', sa.Column('origin_city', sa.String(), nullable=True))
    op.add_column('user', sa.Column('origin_barangay', sa.String(), nullable=True))
    op.add_column('user', sa.Column('origin_address', sa.String(), nullable=True))
    op.add_column('user', sa.Column('origin_region_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('origin_city_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('origin_barangay_code', sa.String(), nullable=True))
    op.drop_column('user', 'provincial_region')
    op.drop_column('user', 'provincial_barangay_code')
    op.drop_column('user', 'provincial_address')
    op.drop_column('user', 'provincial_city_code')
    op.drop_column('user', 'provincial_region_code')
    op.drop_column('user', 'provincial_barangay')
    op.drop_column('user', 'provincial_city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('provincial_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('provincial_barangay', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('provincial_region_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('provincial_city_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('provincial_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('provincial_barangay_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('provincial_region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'origin_barangay_code')
    op.drop_column('user', 'origin_city_code')
    op.drop_column('user', 'origin_region_code')
    op.drop_column('user', 'origin_address')
    op.drop_column('user', 'origin_barangay')
    op.drop_column('user', 'origin_city')
    op.drop_column('user', 'origin_region')
    op.drop_column('user', 'origin_country')
    op.drop_column('user', 'origin_is_international')
    # ### end Alembic commands ###
