"""update course

Revision ID: 11fb44f26263
Revises: 58100512e0c9
Create Date: 2023-11-10 12:32:58.287239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11fb44f26263'
down_revision: Union[str, None] = '58100512e0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_user_id_fkey', 'course', type_='foreignkey')
    op.drop_column('course', 'user_id')
    op.add_column('user', sa.Column('course_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'user', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'course_id')
    op.add_column('course', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('course_user_id_fkey', 'course', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
