"""remove provinces

Revision ID: 1268b9f38d64
Revises: fd4052304b7d
Create Date: 2023-11-24 02:13:12.678752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1268b9f38d64'
down_revision: Union[str, None] = 'fd4052304b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('education', 'province')
    op.drop_column('employment', 'province')
    op.drop_column('user', 'province')
    op.drop_column('user', 'provincial_province')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('provincial_province', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('province', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employment', sa.Column('province', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('province', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
