"""modified the last night's data

Revision ID: 1eeebeaeaf6a
Revises: 46c822bf87db
Create Date: 2023-11-23 09:30:02.579291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eeebeaeaf6a'
down_revision: Union[str, None] = '46c822bf87db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('education', sa.Column('is_international', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('education', sa.Column('country', sa.String(), server_default='philippines', nullable=True))
    op.add_column('education', sa.Column('region', sa.String(), nullable=True))
    op.add_column('education', sa.Column('province', sa.String(), nullable=True))
    op.add_column('education', sa.Column('city', sa.String(), nullable=True))
    op.add_column('education', sa.Column('barangay', sa.String(), nullable=True))
    op.add_column('education', sa.Column('address', sa.String(), nullable=True))
    op.alter_column('education', 'level',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('education', 'story',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('education', 'link_reference')
    op.drop_column('education', 'type_of_achievement')
    op.add_column('employment', sa.Column('province', sa.String(), nullable=True))
    op.add_column('employment', sa.Column('address', sa.String(), nullable=True))
    op.create_index(op.f('ix_employment_address'), 'employment', ['address'], unique=False)
    op.drop_column('employment', 'barangay')
    op.add_column('user', sa.Column('is_international', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('user', sa.Column('province', sa.String(), nullable=True))
    op.add_column('user', sa.Column('provincial_region', sa.String(), nullable=True))
    op.add_column('user', sa.Column('provincial_province', sa.String(), nullable=True))
    op.add_column('user', sa.Column('provincial_city', sa.String(), nullable=True))
    op.add_column('user', sa.Column('provincial_barangay', sa.String(), nullable=True))
    op.add_column('user', sa.Column('provincial_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'provincial_address')
    op.drop_column('user', 'provincial_barangay')
    op.drop_column('user', 'provincial_city')
    op.drop_column('user', 'provincial_province')
    op.drop_column('user', 'provincial_region')
    op.drop_column('user', 'province')
    op.drop_column('user', 'is_international')
    op.add_column('employment', sa.Column('barangay', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_employment_address'), table_name='employment')
    op.drop_column('employment', 'address')
    op.drop_column('employment', 'province')
    op.add_column('education', sa.Column('type_of_achievement', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('link_reference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('education', 'story',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('education', 'level',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('education', 'address')
    op.drop_column('education', 'barangay')
    op.drop_column('education', 'city')
    op.drop_column('education', 'province')
    op.drop_column('education', 'region')
    op.drop_column('education', 'country')
    op.drop_column('education', 'is_international')
    op.drop_table('upload_history')
    # ### end Alembic commands ###
