"""added address codes

Revision ID: 35de5ed46013
Revises: b697bba71be6
Create Date: 2023-11-24 02:27:25.938757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35de5ed46013'
down_revision: Union[str, None] = 'b697bba71be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('region_code', sa.String(), nullable=True))
    op.add_column('education', sa.Column('city_code', sa.String(), nullable=True))
    op.drop_column('education', 'barangay')
    op.add_column('employment', sa.Column('region_code', sa.String(), nullable=True))
    op.add_column('employment', sa.Column('city_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('region_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('city_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('barangay_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('provincial_region_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('provincial_city_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('provincial_barangay_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'provincial_barangay_code')
    op.drop_column('user', 'provincial_city_code')
    op.drop_column('user', 'provincial_region_code')
    op.drop_column('user', 'barangay_code')
    op.drop_column('user', 'city_code')
    op.drop_column('user', 'region_code')
    op.drop_column('employment', 'city_code')
    op.drop_column('employment', 'region_code')
    op.add_column('education', sa.Column('barangay', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('education', 'city_code')
    op.drop_column('education', 'region_code')
    # ### end Alembic commands ###
