"""added data needed in the tracer form

Revision ID: 46c822bf87db
Revises: 9b094a0f68b3
Create Date: 2023-11-23 03:20:29.926426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46c822bf87db'
down_revision: Union[str, None] = '9b094a0f68b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('type_of_achievement', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('course_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('story', sa.String(), nullable=True),
    sa.Column('month_start', sa.Integer(), nullable=True),
    sa.Column('month_graduated', sa.Integer(), nullable=True),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_graduated', sa.Integer(), nullable=True),
    sa.Column('link_reference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('achievement', sa.Column('month_of_attainment', sa.Integer(), nullable=True))
    op.add_column('employment', sa.Column('job_position', sa.String(), nullable=True))
    op.add_column('employment', sa.Column('employer_type', sa.String(), nullable=True))
    op.add_column('employment', sa.Column('country', sa.String(), server_default='philippines', nullable=True))
    op.add_column('employment', sa.Column('region', sa.String(), nullable=True))
    op.add_column('employment', sa.Column('barangay', sa.String(), nullable=True))
    op.alter_column('employment', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employment', 'date_hired',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('employment', 'gross_monthly_income',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employment', 'employment_contract',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user', sa.Column('mobile_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('telephone_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(), server_default='philippines', nullable=True))
    op.add_column('user', sa.Column('region', sa.String(), nullable=True))
    op.add_column('user', sa.Column('barangay', sa.String(), nullable=True))
    op.add_column('user', sa.Column('month_start', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('month_graduated', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('year_start', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'year_start')
    op.drop_column('user', 'month_graduated')
    op.drop_column('user', 'month_start')
    op.drop_column('user', 'barangay')
    op.drop_column('user', 'region')
    op.drop_column('user', 'country')
    op.drop_column('user', 'telephone_number')
    op.drop_column('user', 'mobile_number')
    op.alter_column('employment', 'employment_contract',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employment', 'gross_monthly_income',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employment', 'date_hired',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employment', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('employment', 'barangay')
    op.drop_column('employment', 'region')
    op.drop_column('employment', 'country')
    op.drop_column('employment', 'employer_type')
    op.drop_column('employment', 'job_position')
    op.drop_column('achievement', 'month_of_attainment')
    op.drop_table('education')
    # ### end Alembic commands ###
