"""added achievements

Revision ID: 58100512e0c9
Revises: 155c5bcdb2ce
Create Date: 2023-11-09 23:27:38.411867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58100512e0c9'
down_revision: Union[str, None] = '155c5bcdb2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('type_of_achievement', sa.String(), nullable=True),
    sa.Column('year_of_attainment', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('link_reference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'achievements_story')
    op.drop_column('user', 'achievements')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('achievements', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('achievements_story', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('achievement')
    # ### end Alembic commands ###
