"""revised all the date into dates

Revision ID: 8162be0e2904
Revises: 058d4bde1e30
Create Date: 2023-11-25 00:56:35.144606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8162be0e2904'
down_revision: Union[str, None] = '058d4bde1e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement', sa.Column('date_of_attainment', sa.Date(), nullable=True))
    op.drop_column('achievement', 'year_of_attainment')
    op.drop_column('achievement', 'month_of_attainment')
    op.add_column('education', sa.Column('date_start', sa.Date(), nullable=True))
    op.add_column('education', sa.Column('date_graduated', sa.Date(), nullable=True))
    op.drop_column('education', 'year_graduated')
    op.drop_column('education', 'year_start')
    op.drop_column('education', 'month_graduated')
    op.drop_column('education', 'month_start')
    op.add_column('user', sa.Column('date_start', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('date_graduated', sa.Date(), nullable=True))
    op.drop_column('user', 'year_graduated')
    op.drop_column('user', 'year_start')
    op.drop_column('user', 'month_graduated')
    op.drop_column('user', 'month_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('month_start', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('month_graduated', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('year_start', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('year_graduated', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'date_graduated')
    op.drop_column('user', 'date_start')
    op.add_column('education', sa.Column('month_start', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('month_graduated', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('year_start', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('year_graduated', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('education', 'date_graduated')
    op.drop_column('education', 'date_start')
    op.add_column('achievement', sa.Column('month_of_attainment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('achievement', sa.Column('year_of_attainment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('achievement', 'date_of_attainment')
    # ### end Alembic commands ###
