"""array of string for post_grad_act trial

Revision ID: 823e41048673
Revises: 8ad9f8cdf641
Create Date: 2023-10-03 01:14:15.210937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823e41048673'
down_revision: Union[str, None] = '8ad9f8cdf641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
