"""update classifications

Revision ID: 83f0ee5cfda8
Revises: 11fb44f26263
Create Date: 2023-11-10 21:46:47.719723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83f0ee5cfda8'
down_revision: Union[str, None] = '11fb44f26263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classification', sa.Column('code', sa.String(), nullable=False))
    op.create_index(op.f('ix_classification_code'), 'classification', ['code'], unique=True)
    op.drop_constraint('job_employment_id_fkey', 'job', type_='foreignkey')
    op.drop_column('job', 'employment_id')
    op.drop_constraint('user_course_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('course_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_course_id_fkey', 'user', 'course', ['course_id'], ['id'])
    op.add_column('job', sa.Column('employment_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('job_employment_id_fkey', 'job', 'employment', ['employment_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_classification_code'), table_name='classification')
    op.drop_column('classification', 'code')
    # ### end Alembic commands ###
