"""array of string for post_grad_act trial

Revision ID: 8ad9f8cdf641
Revises: 8879d21e4788
Create Date: 2023-10-03 01:08:45.110713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad9f8cdf641'
down_revision: Union[str, None] = '8879d21e4788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
