"""profile picture and verified

Revision ID: 91bbbda14a31
Revises: 2564b8e19d52
Create Date: 2023-09-29 16:14:32.250936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91bbbda14a31'
down_revision: Union[str, None] = '2564b8e19d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verified',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verified',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
