"""added sub column

Revision ID: 93e7fb8d7ae8
Revises: c954fd055292
Create Date: 2023-10-16 04:14:11.792771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e7fb8d7ae8'
down_revision: Union[str, None] = 'c954fd055292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sub', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_sub'), 'users', ['sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sub'), table_name='users')
    op.drop_column('users', 'sub')
    # ### end Alembic commands ###
