"""update classifications

Revision ID: c851e4638178
Revises: 83f0ee5cfda8
Create Date: 2023-11-10 22:07:38.903162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c851e4638178'
down_revision: Union[str, None] = '83f0ee5cfda8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employment', sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'employment', 'job', ['job_id'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('course_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'user', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'course_id')
    op.drop_constraint(None, 'employment', type_='foreignkey')
    op.drop_column('employment', 'job_id')
    # ### end Alembic commands ###
