"""removed post_grad_act column

Revision ID: cfd1f74f0798
Revises: 823e41048673
Create Date: 2023-10-03 01:20:02.846653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd1f74f0798'
down_revision: Union[str, None] = '823e41048673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'post_grad_act')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('post_grad_act', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
