"""first init

Revision ID: db9b6599c0b2
Revises: 
Create Date: 2023-09-22 02:27:45.687839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9b6599c0b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_programs_id'), 'academic_programs', ['id'], unique=False)
    op.create_index(op.f('ix_academic_programs_name'), 'academic_programs', ['name'], unique=True)
    op.create_table('prc_certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_name', sa.String(), nullable=False),
    sa.Column('prc_title', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_name'),
    sa.UniqueConstraint('prc_title')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), server_default='kalabaw', nullable=False),
    sa.Column('last_name', sa.String(), server_default='kalabaw', nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('profile_picture', sa.String(), server_default='#', nullable=True),
    sa.Column('verified', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('role', sa.String(), server_default='alumni', nullable=False),
    sa.Column('student_number', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('barangay', sa.String(), nullable=True),
    sa.Column('year_graduated', sa.Integer(), nullable=True),
    sa.Column('telephone_number', sa.String(), nullable=True),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('civil_status', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('academic_program_id', sa.UUID(), nullable=True),
    sa.Column('civil_service_eligibility', sa.Boolean(), nullable=True),
    sa.Column('present_employment_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['academic_program_id'], ['academic_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_student_number'), 'users', ['student_number'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alumni_certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alumni_id', sa.UUID(), nullable=False),
    sa.Column('prc_certification_id', sa.UUID(), nullable=False),
    sa.Column('certificate_number', sa.String(), nullable=False),
    sa.Column('certification_date', sa.Date(), nullable=False),
    sa.Column('certification_authority', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['alumni_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prc_certification_id'], ['prc_certifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alumni_id', sa.UUID(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('date_hired', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('aligned_with_academic_program', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('gross_monthly_income', sa.String(), nullable=False),
    sa.Column('employment_contract', sa.String(), nullable=False),
    sa.Column('job_level_position', sa.String(), nullable=False),
    sa.Column('type_of_employer', sa.String(), nullable=False),
    sa.Column('location_of_employment', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alumni_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alumni_id', sa.UUID(), nullable=True),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('star_rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alumni_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special_skills_certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alumni_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alumni_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('special_skills_certifications')
    op.drop_table('feedbacks')
    op.drop_table('employment')
    op.drop_table('alumni_certifications')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_student_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('prc_certifications')
    op.drop_index(op.f('ix_academic_programs_name'), table_name='academic_programs')
    op.drop_index(op.f('ix_academic_programs_id'), table_name='academic_programs')
    op.drop_table('academic_programs')
    # ### end Alembic commands ###
