"""really? ambobo mo hayme

Revision ID: e3fdd1a8b252
Revises: 685d63cad378
Create Date: 2023-10-03 13:59:01.221081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3fdd1a8b252'
down_revision: Union[str, None] = '685d63cad378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_employment_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'employment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employment_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_employment_id_fkey', 'users', 'employment', ['employment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
