"""maam che updates

Revision ID: fce986221019
Revises: f19c30014e5b
Create Date: 2023-12-07 02:39:49.289618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fce986221019'
down_revision: Union[str, None] = 'f19c30014e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('national_certification',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('issuing_body', sa.String(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('link_reference', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('national_certification_classification',
    sa.Column('national_certification_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('classification_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classification.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['national_certification_id'], ['national_certification.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('national_certification_id', 'classification_id')
    )
    op.add_column('achievement', sa.Column('national_certification_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_achievement_national_certification', 'achievement', 'national_certification', ['national_certification_id'], ['id'], ondelete='CASCADE')
    op.add_column('course', sa.Column('in_pupqc', sa.Boolean(), server_default='False', nullable=False))
    op.drop_column('upload_history', 'group')
    op.add_column('user', sa.Column('unemployment_reason', postgresql.ARRAY(sa.String()), nullable=True, server_default=None))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'unemployment_reason')
    op.alter_column('upload_history', 'group',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('course', 'in_pupqc')
    op.drop_constraint(None, 'achievement', type_='foreignkey')
    op.drop_column('achievement', 'national_certification_id')
    op.drop_table('national_certification_classification')
    op.drop_table('national_certification')
    # ### end Alembic commands ###
