"""first revision

Revision ID: e622a4769b67
Revises: 
Create Date: 2023-08-28 19:34:31.226392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e622a4769b67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Questions_id'), 'Questions', ['id'], unique=False)
    op.create_table('Choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('choice_text', sa.String(), nullable=True),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.Column('questionID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questionID'], ['Questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Choices_choice_text'), 'Choices', ['choice_text'], unique=False)
    op.create_index(op.f('ix_Choices_id'), 'Choices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Choices_id'), table_name='Choices')
    op.drop_index(op.f('ix_Choices_choice_text'), table_name='Choices')
    op.drop_table('Choices')
    op.drop_index(op.f('ix_Questions_id'), table_name='Questions')
    op.drop_table('Questions')
    # ### end Alembic commands ###
