"""Initiated Index on question_text

Revision ID: ff9a99044c65
Revises: e622a4769b67
Create Date: 2023-08-28 19:36:32.719293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9a99044c65'
down_revision: Union[str, None] = 'e622a4769b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Questions_question_text'), 'Questions', ['question_text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Questions_question_text'), table_name='Questions')
    # ### end Alembic commands ###
