"""verified column under Alumni table

Revision ID: 0d640c5c19f3
Revises: 22329153077e
Create Date: 2023-09-09 02:07:17.383035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d640c5c19f3'
down_revision: Union[str, None] = '22329153077e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumni', 'verified')
    # ### end Alembic commands ###
