"""removed emailadd

Revision ID: 7f020db9c638
Revises: 576308ffe0f0
Create Date: 2023-09-19 14:55:45.397680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f020db9c638'
down_revision: Union[str, None] = '576308ffe0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
